# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Job definition templates

  baseline-job: &baseline-job
    template: baseline.jinja2
    kind: job
    kcidb_test_suite: boot

  kbuild-job: &kbuild-job
    template: kbuild.jinja2
    kind: kbuild
    rules:
      tree:
      - '!android'
      - '!chromiumos'

  ltp-job: &ltp-job
    template: ltp.jinja2
    kind: job
    params: &ltp-params
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-ltp/20240313.0/{debarch}'
      skip_install: "true"
      skipfile: skipfile-lkft.yaml
    kcidb_test_suite: ltp
    rules:
      fragments:
        - '!kselftest'

jobs:

  # FIXME This will need to be reworked later when the fstests scheduler has
  # been removed
  #
  # fstests:
  #   template: 'fstests.jinja2'
  #   image: 'kernelci/staging-kernelci'

  baseline-riscv-cloudv: *baseline-job

  kbuild-clang-17-riscv: &kbuild-clang-17-riscv-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}clang-17:riscv64-kselftest-kernelci
    params: &kbuild-clang-17-riscv-params
      arch: riscv
      compiler: clang-17
      cross_compile: 'riscv64-linux-gnu-'
      defconfig: defconfig

  kbuild-clang-17-riscv-mainline: &kbuild-clang-17-riscv-mainline-job
    <<: *kbuild-clang-17-riscv-job
    params: &kbuild-clang-17-riscv-mainline-params
      <<: *kbuild-clang-17-riscv-params
      fragments:
        - 'debug'
        - 'kselftest'
        - 'tinyconfig'
    rules:
      min_version:
        version: 4
        patchlevel: 15
      tree:
        - 'mainline'

  kbuild-clang-17-riscv-mainline-allnoconfig:
    <<: *kbuild-clang-17-riscv-mainline-job
    params:
      <<: *kbuild-clang-17-riscv-mainline-params
      defconfig:
      - defconfig
      - allnoconfig

  kbuild-clang-17-riscv-nommu_k210_defconfig:
    <<: *kbuild-clang-17-riscv-job
    params:
      <<: *kbuild-clang-17-riscv-params
      defconfig: nommu_k210_defconfig
    rules:
      min_version:
        version: 5
        patchlevel: 10
      tree:
      - 'kernelci'
      - 'stable-rc'
      - 'stable'

  # Named so it sorts before all the actual kselftests, we need to
  # specify a kselftest suite for YAML validation.
  kselftest-aaa: &kselftest-job
    template: generic.jinja2
    kind: job
    params: &kselftest-params
      test_method: kselftest
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-kselftest/20250117.0/{debarch}'
      job_timeout: 10
    rules: &kselftest-rules
      tree:
        - mainline
        - next
        - stable-rc
        - stable
    kcidb_test_suite: kselftest.aaa

  kselftest-alsa:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: alsa
    kcidb_test_suite: kselftest.alsa

  kselftest-arm64:
    <<: *kselftest-job
    template: generic.jinja2
    kind: job
    params:
      <<: *kselftest-params
      collections: arm64
    kcidb_test_suite: kselftest.arm64

  kselftest-capabilities:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: capabilities
    kcidb_test_suite: kselftest.capabilities

  kselftest-clone3:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: clone3
    kcidb_test_suite: kselftest.clone3

  kselftest-cpufreq:
    <<: *kselftest-job
    template: generic.jinja2
    kind: job
    params:
      <<: *kselftest-params
      collections: cpufreq
    kcidb_test_suite: kselftest.cpufreq

  kselftest-cpufreq-hibernate:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: cpufreq
      env: 'KSELFTEST_MAIN_SH_ARGS="-t hibernate_rtc"'
    rules:
      <<: *kselftest-rules
      min_version:
        version: 6
        patchlevel: 12
    kcidb_test_suite: kselftest.cpufreq.hibernate

  kselftest-cpufreq-suspend:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: cpufreq
      env: 'KSELFTEST_MAIN_SH_ARGS="-t suspend_rtc"'
    rules:
      <<: *kselftest-rules
      min_version:
        version: 6
        patchlevel: 12
    kcidb_test_suite: kselftest.cpufreq.suspend

  kselftest-devices-exist:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      test_method: kselftest-platform-parameters
      collections: devices/exist
      env: "KSELFTEST_TEST_DEV_EXIST_PY_ARGS=--reference-dir=/opt/platform-test-parameters-main/kselftest/devices/exist/"
    rules:
      tree:
        - collabora-next:for-kernelci
    kcidb_test_suite: kselftest.devices-exist

  kselftest-device-error-logs-main:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: devices/error_logs
    kcidb_test_suite: kselftest.device_error_logs

  kselftest-devices-probe:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: devices/probe
      env: "KSELFTEST_TEST_DISCOVERABLE_DEVICES_PY_ARGS=--boards-dir=/opt/platform-test-parameters/kselftest/test_discoverable_devices/boards/"
    rules:
      <<: *kselftest-rules
      min_version:
        version: 6
        patchlevel: 11
    kcidb_test_suite: kselftest.devices-probe

  kselftest-dmabuf-heaps:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: dmabuf-heaps
    kcidb_test_suite: kselftest.dmabuf-heaps

  kselftest-dt:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: dt
    rules:
      <<: *kselftest-rules
      min_version:
        version: 6
        patchlevel: 7
    kcidb_test_suite: kselftest.dt

  kselftest-exec:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: exec
    kcidb_test_suite: kselftest.exec

  kselftest-ftrace:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: ftrace
    kcidb_test_suite: kselftest.ftrace

  kselftest-futex:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: futex
    kcidb_test_suite: kselftest.futex

  kselftest-iommu:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: iommu
    kcidb_test_suite: kselftest.iommu

  kselftest-ipc:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: ipc
    kcidb_test_suite: kselftest.ipc

  kselftest-kvm:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: kvm
    kcidb_test_suite: kselftest.kvm

  kselftest-landlock:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: landlock
    kcidb_test_suite: kselftest.landlock

  # No hugepages allocation (for architectures without it)
  kselftest-mm:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      extra_kernel_args: "secretmem.enable kpti=off"
      collections: mm
    kcidb_test_suite: kselftest.mm

  # hugepages allocation suitable for machines with 2G of memory
  kselftest-mm-2g:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      extra_kernel_args: "secretmem.enable hugepagesz=32M hugepages=0:4 default_hugepagesz=2M hugepages=0:128 hugepagesz=64K hugepages=0:4 kpti=off"
      collections: mm
    kcidb_test_suite: kselftest.mm

  kselftest-mqueue:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: mqueue
    kcidb_test_suite: kselftest.mqueue

  kselftest-net:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: net
      job_timeout: 300
      skipfile: https://storage.kernelci.org/skipfile-net.yaml
    kcidb_test_suite: kselftest.net

  kselftest-perf-events:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: perf_events
    kcidb_test_suite: kselftest.perf_events

  kselftest-seccomp:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: seccomp
    kcidb_test_suite: kselftest.seccomp

  kselftest-signal:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: signal
    kcidb_test_suite: kselftest.signal

  kselftest-timers:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: timers
    kcidb_test_suite: kselftest.timers

  kselftest-ublk:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: ublk
    kcidb_test_suite: kselftest.ublk

  kselftest-uevent:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: uevent
    kcidb_test_suite: kselftest.uevent

  kselftest-user-events:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: user_events
    kcidb_test_suite: kselftest.user_events

  kselftest-vdso:
    <<: *kselftest-job
    params:
      <<: *kselftest-params
      collections: vDSO
    kcidb_test_suite: kselftest.vdso

  kunit: &kunit-job
    template: kunit.jinja2
    kind: job
    image: ghcr.io/kernelci/{image_prefix}gcc-12:x86-kunit-kernelci
    kcidb_test_suite: kunit
    rules:
      tree:
      - '!chromiumos'

  kunit-x86_64:
    <<: *kunit-job
    params:
      arch: x86_64

  ltp-cap-bounds:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "cap_bounds"

  ltp-containers:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "containers"

  ltp-controllers:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "controllers"

  ltp-cpuhotplug:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "cpuhotplug"

  ltp-crypto:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "crypto"
    rules:
      fragments:
        - 'crypto'
        - '!kselftest'

  ltp-cve:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "cve"
      job_timeout: 45

  ltp-dio:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "dio"

  ltp-fcntl-locktests:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fcntl-locktests"

  ltp-filecaps:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "filecaps"

  ltp-fs:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fs"

  ltp-fs-bind:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fs_bind"

  ltp-fs-perms-simple:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fs_perms_simple"

  ltp-fs-readonly:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fs_readonly"

  ltp-fsx:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "fsx"

  ltp-hugetlb:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "hugetlb"

  ltp-ima:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "ima"
    rules:
      fragments:
        - 'ima'
        - '!kselftest'

  ltp-input:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "input"

  ltp-io:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "io"

  ltp-ipc:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "ipc"

  ltp-mm:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "mm"
      job_timeout: 30

  ltp-pty:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "pty"
      job_timeout: 25

  ltp-sched:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "sched"

  ltp-smoketest:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "smoketest"

  ltp-syscalls:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "syscalls"
      job_timeout: 120

  ltp-syscalls-ipc:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "syscalls"

  ltp-timers:
    <<: *ltp-job
    params:
      <<: *ltp-params
      grp_test: "TMR"
      job_timeout: 30

  ltp-timers_qemu:
    <<: *ltp-job
    base_name: ltp-timers
    params:
      <<: *ltp-params
      grp_test: "TMR"
      job_timeout: 30
    rules:
      defconfig:
        - 'defconfig'
      fragments:
        - '!kselftest'

  ltp-watchqueue:
    <<: *ltp-job
    params:
      <<: *ltp-params
      tst_cmdfiles: "watchqueue"

  rt-tests: &rt-tests
    template: rt-tests.jinja2
    kind: job
    params: &rt-tests-params
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-rt/20240806.0/{debarch}'
    kcidb_test_suite: rt-tests
    rules:
      fragments:
        - preempt_rt

  rt-tests-cyclicdeadline:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'cyclicdeadline'
    kcidb_test_suite: rt-tests.cyclicdeadline

  rt-tests-cyclictest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'cyclictest'
    kcidb_test_suite: rt-tests.cyclictest

  rt-tests-pi-stress:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'pi-stress'
    kcidb_test_suite: rt-tests.pi-params

  rt-tests-pmqtest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'pmqtest'
    kcidb_test_suite: rt-tests.pmqtest

  rt-tests-ptsematest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'ptsematest'
    kcidb_test_suite: rt-tests.ptsematest

  rt-tests-rt-migrate-test:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'rt-migrate-test'
    kcidb_test_suite: rt-tests.rt-migrate-test

  rt-tests-rtla-osnoise:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'rtla-osnoise'
      tst_group: 'rtla'
    kcidb_test_suite: rt-tests.rtla-osnoise

  rt-tests-rtla-timerlat:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'rtla-timerlat'
      tst_group: 'rtla'
    kcidb_test_suite: rt-tests.rtla-timerlat

  rt-tests-signaltest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'signaltest'
    kcidb_test_suite: rt-tests.signaltest

  rt-tests-sigwaittest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'sigwaittest'
    kcidb_test_suite: rt-tests.sigwaittest

  rt-tests-svsematest:
    <<: *rt-tests
    params:
      <<: *rt-tests-params
      tst_cmd: 'svsematest'
    kcidb_test_suite: rt-tests.svsematest

  # amd64-only temporary
  sleep:
    template: generic.jinja2
    kind: job
    params:
      test_method: sleep
      boot_commands: nfs
      nfsroot: http://storage.kernelci.org/images/rootfs/debian/bullseye/20240129.0/{debarch}
      sleep_params: mem freeze
    kcidb_test_suite: kernelci_sleep

  h26forge-debian:
    template: generic.jinja2
    kind: job
    params:
      test_method: h26forge-debian
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-gst-h26forge/20250117.0/{debarch}/'
    rules:
      tree:
        - media
    kcidb_test_suite: h26forge.debian

  wifi-basic:
    template: generic.jinja2
    kind: job
    params:
      test_method: wifi-basic
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-wifi/20240313.0/{debarch}/'
    rules:
      tree:
        - mainline
        - stable-rc
    kcidb_test_suite: kernelci_wifi_basic
  
  nipa-update:
    template: nipa-update.jinja2
    kind: test
    image: kernelci/{image_prefix}kernelci
    kcidb_test_suite: kernelci_nipa-update
    rules:
      tree:
        - netdev-testing
