# The default configuration is used for all the jobs that don't have a specific configuration
[DEFAULT]
api_config = "docker-host"
storage_config = "docker-host"
verbose = true

[trigger]
force = 1
# how often to poll git trees for new commits
poll_period = 0
# delay first git poll after startup
startup_delay = 3
# checkout default timeout
timeout = 180

[tarball]
# where to store git tree sources, relative to tarball process
kdir = "/home/kernelci/data/src/linux"
# where to store tarballs, relative to tarball process
output = "/home/kernelci/data/output"
# which storage service to use
storage_config = "docker-host"

[patchset]
kdir = "/home/kernelci/data/src/linux-patchset"
output = "/home/kernelci/data/output"
storage_config = "docker-host"
patchset_tmp_file_prefix = "kernel-patch"
patchset_short_hash_len = 13
# domains allowed to fetch patches from
allowed_domains = ["patchwork.kernel.org"]
polling_delay_secs = 30

[scheduler]
# directory to store temporary job templates
output = "/home/kernelci/data/output"

[notifier]

[send_kcidb]
kcidb_topic_name = "localhost"
kcidb_project_id = "localhost"
database_name = "localhost"
postgresql_host = "localhost"
postgresql_port = 5432
postgresql_user = "kernelci.org"
postgresql_password = "password"
origin = "maestro"

[test_report]
email_sender = "bot@kernelci.org"
email_recipient = "kernelci-results-staging@groups.io"
# smtp_host = "smtp.yourserver.com"
# smtp_port = 465

[timeout]

[regression_tracker]

[storage.docker-host]
storage_cred = "/home/kernelci/data/ssh/id_rsa_tarball"

[jwt]
# JWT secret to generate Pipeline API tokens
secret = "0123456789"

[runtime.lava-cloudv]
runtime_token = "j5cuu2wgj5lijzgaqb2eoec30qkfqi6h83dapee4ex3k1rml0faex0z0t8rr04ownlemuw6es5zj6l5ukqi0pimglghc50la41e6c2wagbt7ikw99ypkcasbsaqzwy02"
callback_token = "j5cuu2wgj5lijzgaqb2eoec30qkfqi6h83dapee4ex3k1rml0faex0z0t8rr04ownlemuw6es5zj6l5ukqi0pimglghc50la41e6c2wagbt7ikw99ypkcasbsaqzwy02"

