# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

api:

  docker-host:
    url: http://172.17.0.1:8001

storage:

  docker-host:
    storage_type: ssh
    host: 172.17.0.1
    port: 8022
    base_url: http://172.17.0.1:8002/

runtimes:

  docker:
    lab_type: docker
    env_file: '/home/kernelci/.docker-env'
    user: 'root'  # Docker-in-Docker
    volumes:
      # Note: Absolute paths on the host are required here
      - '/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/kernelci/kernelci-pipeline/data/ssh/:/home/kernelci/data/ssh'
      - '/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/kernelci/kernelci-pipeline/data/output/:/home/kernelci/data/output'

  lava-local:
    lab_type: lava
    url: 'http://lava-master-local:10070/'
    notify:
      callback:
        token: local-kernelci-token
    rules:
      tree:
      - 'mainline'

