# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Device definition templates

  riscv-device: &riscv-device
    arch: riscv
    boot_method: u-boot


platforms:

  qemu:
    base_name: qemu
    arch: riscv64
    boot_method: qemu
    mach: qemu
    context:
      arch: riscv64
      machine: virt
      guestfs_interface: virtio

  docker:

  jh7100-starfive-visionfive-v1:
    <<: *riscv-device
    mach: starfive
    dtb: dtbs/starfive/jh7100-starfive-visionfive-v1.dtb
    compatible: ["starfive,visionfive-v1", "starfive,jh7100"]
