# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Scheduler definition helpers
  build-docker: &build-docker
    event: &checkout-event
      channel: node
      kind: checkout
      state: available
    runtime:
      name: docker

  node-event: &node-event-kbuild
    channel: node
    result: pass
    kind: kbuild

  job-event: &job-event
    channel: node
    state: done
    kind: job


scheduler:

  - job: baseline-riscv-cloudv
    event: &kbuild-clang-17-riscv-node-event
      <<: *node-event-kbuild
      name: kbuild-clang-17-riscv
    runtime: &lava-local-runtime
      type: lava
      name: lava-local
    platforms:
      - qemu

  - job: kbuild-clang-17-riscv
    <<: *build-docker
    rules:
      tree:
        - 'mainline'
