trees:

  mainline:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'

# -----------------------------------------------------------------------------
# Legacy configuration data (still used by trigger service)
#

build_environments:

  clang-17:
    cc: clang
    cc_version: 17
    arch_params:
      riscv:
        name: 'riscv'


build_variants:
  variants:
    clang-17:
      build_environment: clang-17
      architectures:
        riscv:
          base_defconfig: 'defconfig'
          filters:
            - regex: { defconfig: 'defconfig' }


build_configs:

  mainline: &mainline
    tree: mainline
    branch: 'master'

  mainline-riscv: &mainline-riscv
    <<: *mainline
    architectures:
      - riscv